"""SchemaWriter — render a SchemaDocument as a human-readable Markdown reference.

The output is intended to be checked into Ophamin's repo as ``KIMERA_FIELDS.md``,
one document per Kimera commit. A diff between two such files surfaces every
new / removed / type-changed field across Kimera commits — the literal mechanic
that lets Ophamin co-evolve with Kimera.
"""

from __future__ import annotations

from pathlib import Path

from ophamin.seeing.discovery.schema_document import (
    FieldSchema,
    SchemaDocument,
    TargetSchema,
)


def _format_sample(field: FieldSchema) -> str:
    if not field.sample_values:
        return "—"
    if field.sample_kind == "lengths":
        return "lengths: " + ", ".join(str(v) for v in field.sample_values)
    parts = []
    for v in field.sample_values:
        if isinstance(v, str):
            parts.append(f'"{v}"')
        else:
            parts.append(repr(v))
    return ", ".join(parts)


def _format_target_section(target: TargetSchema) -> str:
    header = (
        f"### Target: `{target.name}`\n\n"
        f"- class: `{target.target_class}`\n"
        f"- cycles: {target.n_cycles}  "
        f"(adapter errors: {target.n_adapter_errors})\n"
        f"- field paths observed: {len(target.fields)}\n\n"
    )
    if not target.fields:
        return header + "_No fields observed._\n\n"
    rows = [
        "| path | types | occurrence | samples |",
        "|---|---|---|---|",
    ]
    for fld in target.fields:
        types = ", ".join(f"`{t}`" for t in fld.types_seen) or "—"
        occ = (
            f"{fld.occurrence_count}/{fld.n_cycles_target} "
            f"({fld.occurrence_rate:.0%})"
        )
        rows.append(
            f"| `{fld.path}` | {types} | {occ} | {_format_sample(fld)} |"
        )
    return header + "\n".join(rows) + "\n\n"


def write_schema_markdown(doc: SchemaDocument, path: str | Path) -> Path:
    """Render the SchemaDocument and write it to ``path``. Returns the path."""
    out_path = Path(path)
    lines: list[str] = []
    lines.append("# Kimera field-schema reference\n")
    lines.append(
        "_Auto-generated by Ophamin's discovery layer (Layer A of the "
        "Kimera-co-evolution stack)._\n"
    )
    lines.append("\n## Provenance\n")
    lines.append(f"- captured at: `{doc.captured_at}`\n")
    lines.append(f"- ophamin version: `{doc.ophamin_version}`\n")
    lines.append(f"- ophamin git commit: `{doc.ophamin_git_commit}`\n")
    lines.append(f"- kimera git commit: `{doc.kimera_git_commit}`\n")
    lines.append(f"- stimulus-set content hash: `{doc.stimulus_set_hash}`\n")
    lines.append(f"- stimulus count: `{doc.n_stimuli}`\n")
    lines.append(f"- targets probed: {len(doc.targets)}\n\n")
    lines.append("## Per-target field schemas\n\n")
    for target in doc.targets:
        lines.append(_format_target_section(target))
    out_path.write_text("".join(lines))
    return out_path
