{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "ophamin.serviceAccountName" . }}
  labels:
    {{- include "ophamin.labels" . | nindent 4 }}
  {{- $annotations := include "ophamin.serviceAccount.annotations" . }}
  {{- if $annotations }}
  annotations:
    {{- $annotations | nindent 4 }}
  {{- end }}
{{- end }}
